# FROM openjdk:8-jdk-alpine
# VOLUME /tmp
# ARG JAR_FILE
# COPY /target/jenkins_sample-0.0.1-SNAPSHOT.jar app.jar
# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar","/app.jar"]
FROM java:8
ADD /target/jenkins_sample-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /pegasus.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-jar","/app.jar"]
 